DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS collection;

CREATE TABLE user (
    userID INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE collection (
	gameID INTEGER PRIMARY KEY AUTOINCREMENT,
	ownedBy INTEGER NOT NULL,
	gameName TEXT NOT NULL,
	playtime INTEGER NOT NULL,
	FOREIGN KEY (ownedBy) REFERENCES user(userID)
);
